[project]
name = "homeassistant-trakt"
readme = "README.md"
authors = [{name = "Joshua Peek"}]
requires-python = ">=3.12.0"
classifiers = [
    "License :: OSI Approved :: MIT License",
]

[project.optional-dependencies]
dev = [
    "homeassistant>=2024.4.0",
    "mypy>=1.0.0,<2.0",
    "ruff>=0.3.0",
]

[tool.ruff.lint]
extend-select = ["I", "UP"]

[tool.mypy]
strict = true
