[project]
name = "homeassistant-trakt"
readme = "README.md"
authors = [{name = "Joshua Peek"}]
requires-python = ">=3.10.0"
classifiers = [
    "License :: OSI Approved :: MIT License",
]

[tool.ruff.lint]
extend-select = ["I", "UP"]

[tool.mypy]
strict = false
