name: "Validate"

on: push

jobs:
  hassfest:
    name: "Hassfest Validation"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: home-assistant/actions/hassfest@868e6cb4607727d764341a158d98872cd63fa658 # master

  hacs:
    name: "HACS Validation"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: hacs/action@1ebf01c408f29afcb6406bd431bc98fd8cbb15aa # main
        with:
          category: "integration"
          ignore: "brands"
